### PR TITLE
PDS-853: Retrieve and use latest context products from EN Registry

### PR DESCRIPTION
**Pull request by jordanpadams**
Added a flag (-u) that specifies that the latest JSON context should be
download (and replace the existing file).

### CODE REVIEW

**Comment by jordanpadams** [comment]
@danyu-pds please take a look at this PR and Approve if it looks valid to you. here is the equivalent from our private EN repo: https://github.jpl.nasa.gov/PDSEN/pds4-java/pull/114

**Comment by danyu-pds** [comment]
I have checked all changed files, they are look valid to me. But I noticed the dev branch is different from the dev branch in  our private EN repo: https://github.jpl.nasa.gov/PDSEN/pds4-java.

**Comment by jordanpadams** [comment]
@danyu-pds great catch! just pinged @nutjob4life about this. we may need to rework this

**Comment by jordanpadams** [comment]
Closing this PR to move to new repo

**Pull request closed without merging**
